-- Supabase Database Schema for TradeAgent
-- Trading system for paper trading with performance tracking

-- Daily Performance Metrics
CREATE TABLE IF NOT EXISTS daily_performance (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    total_trades INTEGER NOT NULL DEFAULT 0,
    winning_trades INTEGER NOT NULL DEFAULT 0,
    losing_trades INTEGER NOT NULL DEFAULT 0,
    win_rate DECIMAL(5,4) NOT NULL DEFAULT 0,
    daily_pnl DECIMAL(12,2) NOT NULL DEFAULT 0,
    profit_factor DECIMAL(10,4) NOT NULL DEFAULT 0,
    avg_win DECIMAL(12,2) NOT NULL DEFAULT 0,
    avg_loss DECIMAL(12,2) NOT NULL DEFAULT 0,
    portfolio_value DECIMAL(15,2),
    cash DECIMAL(15,2),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Trade Execution Log
CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    action VARCHAR(4) NOT NULL CHECK (action IN ('BUY', 'SELL')),
    quantity DECIMAL(15,6) NOT NULL,
    entry_price DECIMAL(12,4) NOT NULL,
    exit_price DECIMAL(12,4),
    exit_reason VARCHAR(20) CHECK (exit_reason IN ('stop_loss', 'take_profit', 'technical_exit', 'rebalance')),
    pnl DECIMAL(12,2),
    pnl_pct DECIMAL(8,4),

    -- Strategy Information
    strategy VARCHAR(20) NOT NULL CHECK (strategy IN ('defensive', 'momentum')),

    -- Technical Context
    rsi DECIMAL(5,2),
    macd_histogram DECIMAL(12,6),
    volume_ratio DECIMAL(8,4),

    -- External References
    alpaca_order_id VARCHAR(100),

    created_at TIMESTAMP DEFAULT NOW()
);

-- Trading Signals Log
CREATE TABLE IF NOT EXISTS signals (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD')),
    confidence DECIMAL(3,2) NOT NULL,
    entry_price DECIMAL(12,4) NOT NULL,
    stop_loss DECIMAL(12,4),
    take_profit DECIMAL(12,4),

    -- Technical Context
    rsi DECIMAL(5,2),
    macd_histogram DECIMAL(12,6),
    volume_ratio DECIMAL(8,4),

    -- Execution Status
    strategy VARCHAR(20) NOT NULL,
    executed BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT NOW()
);

-- Strategy-Specific Performance Metrics
CREATE TABLE IF NOT EXISTS strategy_metrics (
    id SERIAL PRIMARY KEY,
    strategy VARCHAR(20) NOT NULL CHECK (strategy IN ('defensive', 'momentum')),
    date DATE NOT NULL,
    total_trades INTEGER NOT NULL DEFAULT 0,
    winning_trades INTEGER NOT NULL DEFAULT 0,
    losing_trades INTEGER NOT NULL DEFAULT 0,
    win_rate DECIMAL(5,4) NOT NULL DEFAULT 0,
    total_pnl DECIMAL(12,2) NOT NULL DEFAULT 0,
    avg_win DECIMAL(12,2),
    avg_loss DECIMAL(12,2),
    profit_factor DECIMAL(10,4),
    sharpe_ratio DECIMAL(5,3),
    max_drawdown DECIMAL(5,2),

    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(strategy, date)
);

-- Parameter Change Log
CREATE TABLE IF NOT EXISTS parameter_changes (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    reason TEXT NOT NULL,
    old_params JSONB NOT NULL,
    new_params JSONB NOT NULL,

    created_at TIMESTAMP DEFAULT NOW()
);

-- Weekly Performance Reports
CREATE TABLE IF NOT EXISTS weekly_reports (
    id SERIAL PRIMARY KEY,
    week_ending DATE NOT NULL UNIQUE,
    total_trades INTEGER NOT NULL DEFAULT 0,
    win_rate DECIMAL(5,4) NOT NULL DEFAULT 0,
    total_pnl DECIMAL(12,2) NOT NULL DEFAULT 0,
    best_performers JSONB,
    worst_performers JSONB,

    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_trades_date ON trades(date DESC);
CREATE INDEX IF NOT EXISTS idx_trades_ticker ON trades(ticker);
CREATE INDEX IF NOT EXISTS idx_trades_strategy ON trades(strategy);
CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(date DESC);
CREATE INDEX IF NOT EXISTS idx_signals_ticker ON signals(ticker);
CREATE INDEX IF NOT EXISTS idx_strategy_metrics_date ON strategy_metrics(date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_performance_date ON daily_performance(date DESC);

-- Comments for Documentation
COMMENT ON TABLE daily_performance IS 'Daily aggregated performance metrics across all strategies';
COMMENT ON TABLE trades IS 'Complete log of all executed trades with entry/exit details';
COMMENT ON TABLE signals IS 'Log of all trading signals generated by strategies';
COMMENT ON TABLE strategy_metrics IS 'Performance metrics broken down by strategy type';
COMMENT ON TABLE parameter_changes IS 'Audit trail of automatic strategy parameter adjustments';
COMMENT ON TABLE weekly_reports IS 'Weekly performance summaries and analysis';
