"""Pydantic models for trading signals and executed trades."""

from datetime import datetime
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, Field


class Signal(BaseModel):
    """Trading signal generated by strategy.

    Attributes:
        ticker: Stock/ETF ticker symbol
        action: Trading action (BUY, SELL, HOLD)
        entry_price: Expected entry price
        stop_loss: Stop-loss price (optional)
        take_profit: Take-profit price (optional)
        confidence: Signal strength (0-1)
        strategy: Strategy that generated the signal
        rsi: RSI indicator value (optional)
        macd_histogram: MACD histogram value (optional)
        volume_ratio: Volume ratio vs average (optional)
        target_value: Target portfolio value for defensive core (optional)
        current_value: Current portfolio value for defensive core (optional)
    """

    ticker: str = Field(description="Stock/ETF ticker symbol")
    action: Literal["BUY", "SELL", "HOLD"] = Field(description="Trading action")
    entry_price: Decimal = Field(description="Expected entry price", gt=0)
    stop_loss: Decimal | None = Field(default=None, description="Stop-loss price", gt=0)
    take_profit: Decimal | None = Field(default=None, description="Take-profit price", gt=0)
    confidence: Decimal = Field(description="Signal strength 0-1", ge=0, le=1)
    strategy: Literal["defensive", "momentum", "news_anomaly", "news_sentiment", "sentiment_trend"] = Field(description="Strategy name")
    metadata: dict | None = Field(default=None, description="Additional metadata")

    # Technical context
    rsi: Decimal | None = Field(default=None, description="RSI indicator value", ge=0, le=100)
    macd_histogram: Decimal | None = Field(default=None, description="MACD histogram value")
    volume_ratio: Decimal | None = Field(default=None, description="Volume ratio", ge=0)

    # Defensive core rebalancing metadata
    target_value: Decimal | None = Field(default=None, description="Target dollar value for position")
    current_value: Decimal | None = Field(default=None, description="Current dollar value of position")


class Trade(BaseModel):
    """Executed trade record for database storage.

    Attributes:
        id: Trade ID (optional, set by database)
        date: Trade execution timestamp
        ticker: Stock/ETF ticker symbol
        action: Trading action (BUY, SELL)
        quantity: Number of shares traded
        entry_price: Entry price per share
        exit_price: Exit price per share (optional, for closed positions)
        exit_reason: Reason for exit (optional)
        pnl: Profit/loss amount (optional)
        pnl_pct: Profit/loss percentage (optional)
        strategy: Strategy that generated the trade
        rsi: RSI value at trade time (optional)
        macd_histogram: MACD histogram at trade time (optional)
        volume_ratio: Volume ratio at trade time (optional)
        alpaca_order_id: Alpaca order ID (optional)
    """

    id: str | None = Field(default=None, description="Trade ID")
    date: datetime = Field(description="Trade execution timestamp")
    ticker: str = Field(description="Stock/ETF ticker symbol")
    action: Literal["BUY", "SELL"] = Field(description="Trading action")
    quantity: Decimal = Field(description="Number of shares traded", gt=0)
    entry_price: Decimal = Field(description="Entry price per share", gt=0)
    exit_price: Decimal | None = Field(default=None, description="Exit price per share", gt=0)
    exit_reason: Literal["stop_loss", "take_profit", "technical_exit", "rebalance"] | None = Field(
        default=None, description="Reason for exit"
    )
    pnl: Decimal | None = Field(default=None, description="Profit/loss amount")
    pnl_pct: Decimal | None = Field(default=None, description="Profit/loss percentage")
    strategy: Literal["defensive", "momentum", "news_anomaly", "news_sentiment", "sentiment_trend"] = Field(description="Strategy name")

    # Technical snapshot
    rsi: Decimal | None = Field(default=None, description="RSI at trade time")
    macd_histogram: Decimal | None = Field(default=None, description="MACD histogram at trade time")
    volume_ratio: Decimal | None = Field(default=None, description="Volume ratio at trade time")
    alpaca_order_id: str | None = Field(default=None, description="Alpaca order ID")
